platform :ios, '9.0'

target 'WoWdb' do
  pod 'React', path: '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'CodePush', path: '../node_modules/react-native-code-push'
  pod 'RNAnalytics', path: '../node_modules/@segment/analytics-react-native'
  pod 'RNAnalyticsIntegration-Google-Analytics', path: '../node_modules/@segment/analytics-react-native-google-analytics'
  pod 'RNGestureHandler', path: '../node_modules/react-native-gesture-handler'
  pod 'SentryReactNative', path: '../node_modules/react-native-sentry'
end

post_install do |installer|
  targets_to_ignore = %w[React yoga]

  installer.pods_project.targets.each do |target|
    target.remove_from_project if targets_to_ignore.include? target.name
  end
end
