update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    increment_build_number(xcodeproj: 'Bigglesworth.xcodeproj')
    build_app(workspace: 'Bigglesworth.xcworkspace', scheme: 'Bigglesworth')
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
