update_fastlane

default_platform(:android)

platform :android do
  lane :beta do
    gradle(task: 'clean assembleRelease')
    upload_to_play_store(track: 'beta')
  end

  lane :deploy do
    gradle(task: 'clean assembleRelease')
    upload_to_play_store
  end
end
